"""External wire vectors, not checksums generated by the code under test."""

from balboa_rs485.protocol.crc import crc8


def test_known_device_present_checksum() -> None:
    # Factual vector from pybalboa tests/test_utils.py; see THIRD_PARTY_NOTICES.md.
    assert crc8(bytes.fromhex("05 0a bf 04")) == 0x77


def test_known_status_checksum() -> None:
    # Independent pybalboa test vector: Fahrenheit, current/target 100, 08:45.
    data = bytes.fromhex("1DFFAF13000064082D00000100000400000000000000000064000000")
    assert crc8(data) == 0x06


def test_empty_checksum() -> None:
    assert crc8(b"") == 0  # Initial register XOR final mask.
