"""Integration identity and configuration keys."""

DOMAIN = "balboa_rs485"
CONF_MODE = "protocol_mode"
CONF_DIRECT_RISK = "accept_direct_bus_risk"
CONF_CONTROLS = "enable_controls"
CONF_OUTDOOR = "outdoor_temperature_entity"
CONF_FALLBACK = "fallback_heating_rate"
CONF_BATH_DURATION = "bathing_duration"
CONF_BATH_MINIMUM = "minimum_bathing_temperature"
