name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  core:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'
      - run: python -m pip install -e '.[dev]'
      - run: python -m tools.dev test -q
      - run: python -m tools.dev lint
      - run: python -m tools.package --check
  home-assistant:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'
          cache: pip
          cache-dependency-path: |
            requirements-ha-test.txt
            pyproject.toml
      - run: python -m pip install -e '.[dev]' -r requirements-ha-test.txt
      - run: python -m pytest tests_ha --ignore=tests_ha/test_installation.py -q --timeout=30 --cov --cov-config=tests_ha/coverage.ini
      - run: python -m pytest tests_ha/test_installation.py -q --timeout=30
        if: ${{ !cancelled() }}
      - run: python -m mypy custom_components/balboa_rs485 --follow-imports=silent --python-version 3.14
        if: ${{ !cancelled() }}
